# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 398)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_password = QtWidgets.QLabel(self.centralwidget)
        self.lbl_password.setGeometry(QtCore.QRect(40, 40, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_password.setFont(font)
        self.lbl_password.setStyleSheet("QLabel{\n"
"border: 2px solid #38b791;\n"
"border-radius: 5px;\n"
"color: #2B244F;\n"
"}\n"
"QLable::hover{\n"
"border: 3px solid rgb(57, 135, 97);\n"
"border-radius: 10px;\n"
"}")
        self.lbl_password.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_password.setObjectName("lbl_password")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 125, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.lbl_lenght = QtWidgets.QLabel(self.centralwidget)
        self.lbl_lenght.setGeometry(QtCore.QRect(150, 125, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_lenght.setFont(font)
        self.lbl_lenght.setStyleSheet("")
        self.lbl_lenght.setObjectName("lbl_lenght")
        self.btn_add_lenght = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_lenght.setGeometry(QtCore.QRect(240, 125, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_add_lenght.setFont(font)
        self.btn_add_lenght.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #38b791;\n"
"color: #FFF;;\n"
"border-radius: 5px;\n"
"cursor: pointer;\n"
"\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(48, 157, 124);\n"
"color:rgb(211, 211, 211);\n"
"}")
        self.btn_add_lenght.setObjectName("btn_add_lenght")
        self.btn_minus_lenght = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus_lenght.setGeometry(QtCore.QRect(298, 125, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_minus_lenght.setFont(font)
        self.btn_minus_lenght.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #38b791;\n"
"color: #FFF;;\n"
"border-radius: 5px;\n"
"cursor: pointer;\n"
"\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(48, 157, 124);\n"
"color:rgb(211, 211, 211);\n"
"}")
        self.btn_minus_lenght.setObjectName("btn_minus_lenght")
        self.uppercase_cbox = QtWidgets.QCheckBox(self.centralwidget)
        self.uppercase_cbox.setGeometry(QtCore.QRect(40, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.uppercase_cbox.setFont(font)
        self.uppercase_cbox.setStyleSheet("")
        self.uppercase_cbox.setObjectName("uppercase_cbox")
        self.special_chars_cbox = QtWidgets.QCheckBox(self.centralwidget)
        self.special_chars_cbox.setGeometry(QtCore.QRect(200, 200, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.special_chars_cbox.setFont(font)
        self.special_chars_cbox.setStyleSheet("")
        self.special_chars_cbox.setObjectName("special_chars_cbox")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(110, 290, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #38b791;\n"
"color: #FFF;;\n"
"border-radius: 8px;\n"
"cursor: pointer;\n"
"\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(48, 157, 124);\n"
"color:rgb(211, 211, 211);\n"
"}")
        self.btnGenerate.setObjectName("btnGenerate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_password.setText(_translate("MainWindow", "password will be shown here"))
        self.label_2.setText(_translate("MainWindow", "Length: "))
        self.lbl_lenght.setText(_translate("MainWindow", "1"))
        self.btn_add_lenght.setText(_translate("MainWindow", "+"))
        self.btn_minus_lenght.setText(_translate("MainWindow", "-"))
        self.uppercase_cbox.setText(_translate("MainWindow", "Uppercase"))
        self.special_chars_cbox.setText(_translate("MainWindow", "special Chars"))
        self.btnGenerate.setText(_translate("MainWindow", "generate"))
